### ISSUE TITLE
Progress of PDF Scripts to txt

### ISSUE THREAD

**Issue by beealex** [beealex/harryPotter#9]
Convert PDFs to text files.
- [x] Sorcerer's Stone
- [x] Chamber of Secrets
- [x] Prisoner of Azkaban
- [x] Goblet of Fire
- [x] Order of the Phoenix 
- [x] Half Blood Prince
- [x] Deathly Hallows Pt. 1
- [x] Deathly Hallows Pt. 2

**Comment by ebeshero** [comment]
@beealex I found Steve Kloves' script of Goblet of Fire on Genius.com (which might be worth looking out for some others on your list too): Take a look: Will this work for your purposes? https://genius.com/Steven-kloves-harry-potter-and-the-goblet-of-fire-script-annotated

**Comment by ebeshero** [comment]
@beealex I notice it's different than the PDF, probably representing the version as it aired?

**Comment by beealex** [comment]
@ebeshero I was checking out genius.com and quickly realized that the Goblet of Fire was the only script available on the website. I thought this was quite odd and very random considering it is the 4th script in the series. I will be verifying the accuracy soon here (genius.com script vs. DVD), but if it is accurate, I think we should just go ahead and use it. Despite the variety of websites we have been using (slug/scriptsavant), I think it will emphasize the lack of open source scripts out there and how hard they are to find. This issue alone would definitely be included in my project analysis and could lead to me clean up the scripts entirely for future students.
